name: surveymonkey
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  envs:
  - key: MONGO_DATABASE_URI
    scope: RUN_AND_BUILD_TIME
    value: mongodb+srv://jonatan:123qweasd@cluster0.otsv5.mongodb.net/?retryWrites=true&w=majority
  github:
    branch: main
    deploy_on_push: true
    repo: markusJsU21/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp
  routes:
  - path: /
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /