databases:
- cluster_name: surveychimp-db
  db_name: dev
  engine: MONGODB
  name: surveychimp-db
  production: true
  version: "5"
name: surveychimp-dev
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${surveychimp-db.DATABASE_URL}
  - key: CA_CERT
    scope: RUN_TIME
    value: ${surveychimp-db.CA_CERT}
  github:
    branch: dev
    deploy_on_push: true
    repo: jonatanhallenberg/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp-api
  routes:
  - path: /api
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /
static_sites:
- build_command: npx nx run build surveychimp-survey-spa
  catchall_document: index.html
  environment_slug: node-js
  envs:
  - key: NX_RATING_STARS_FEATURE
    scope: BUILD_TIME
    value: "false"
  github:
    branch: dev
    deploy_on_push: true
    repo: jonatanhallenberg/surveychimp
  name: surveychimp-survey-spa
  output_dir: dist/apps/surveychimp-survey-spa
  routes:
  - path: /
  source_dir: /
